### ISSUE TITLE
Does this work for Jekyll 4.1.1?

### ISSUE THREAD

**Issue by cpkio** [NiklasEi/jekyll_custom_permalink#3]
I've executed the installations instructions, but it does not seem to work.

>  custom_permalink_placeholders: ["group"]
>  permalink: /:collection/:group/:name/

> C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/url.rb:101:in `block in generate_url_from_drop': The URL template doesn't have group keys. Check your permalink template! (NoMethodError)

**Comment by gfrancesco** [comment]
Works fine for me on Jekyll 4.3.1 and Ruby 3.2.0

**Comment by NiklasEi** [comment]
I haven't used Jekyll or this plugin in a while. At the moment I don't have a setup to check compatibilities.

**Comment by cpkio** [comment]
Still no luck with Ruby 3.20 & Jekyll 4.3.2:
`C:/ruby320-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/url.rb:102:in 'block in generate_url_from_drop': The URL template doesn't have type keys. Check your permalink template! (NoMethodError)`

**Comment by gfrancesco** [comment]
Not sure what can be wrong, but here's my section of `_config.yml` if that can be of any help:

```yaml
collections:
  posts:
    output: true
    custom_permalink_placeholders: ["rnd_id"]
    permalink: blog/:rnd_id/:title
```
